<?php

/*****************************************************
TABLE DEFAULT DEFINES
*****************************************************/

	$table_default_header_top = array(
					'WIDTH' => 6,
					'T_COLOR' => array(0,0,0),
					'T_SIZE' => 6,
					'T_FONT' => 'Arial',
					'T_ALIGN' => 'C',
					'V_ALIGN' => 'T',
					'LN_SIZE' => 3,
					'BG_COLOR' => 'transparent',
					'BRD_COLOR' => array(255,255,255),
					);
					
	$table_default_header_type = array(
					'WIDTH' => 6,
					'T_COLOR' => array(10,10,10),
					'T_SIZE' => 10,
					'T_FONT' => 'Arial',
					'T_ALIGN' => 'C',
					'V_ALIGN' => 'T',
					'T_TYPE' => 'B',
					'LN_SIZE' => 4,
					'BG_COLOR' => array(0,199,229),
// 					'BRD_COLOR' => array(0,92,177),
// 					'BRD_SIZE' => 0.2,
// 					'BRD_TYPE' => '0',
// 					'BRD_TYPE_NEW_PAGE' => '',
					'TEXT' => '',
					);
	$table_default_header_skrd_atas = array(
					'WIDTH' => 6,
					'T_COLOR' => array(0,0,0),
					'T_SIZE' => 6,
					'T_FONT' => 'Arial',
					'T_ALIGN' => 'C',
					'V_ALIGN' => 'T',
					'LN_SIZE' => 3,
					'BG_COLOR' => 'transparent',
					'BRD_COLOR' => array(0,0,0),
					);

	$table_default_header_skrd_gunting = array(
					'WIDTH' => 6,
					'T_COLOR' => array(0,0,0),
					'T_SIZE' => 7,
					'T_FONT' => 'Arial',
					'T_ALIGN' => 'C',
					'V_ALIGN' => 'T',
					'LN_SIZE' => 3,
					'BG_COLOR' => 'transparent',
					'BRD_COLOR' => array(255,255,255),
					);
										
	$table_default_header_skrd_atas_1 = array(
					'WIDTH' => 6,
					'T_COLOR' => array(0,0,0),
					'T_SIZE' => 7,
					'T_FONT' => 'Arial',
					'T_ALIGN' => 'C',
					'V_ALIGN' => 'T',
					'LN_SIZE' => 4,
					'BG_COLOR' => array(255,255,255),
					'BRD_COLOR' => array(0,0,0),
					);
	$table_perikanan_header_type = array(
					'WIDTH' => 6,
					'T_COLOR' => array(0,0,0),
					'T_SIZE' => 10,
					'T_FONT' => 'Arial',
					'T_ALIGN' => 'C',
					'V_ALIGN' => 'T',
					'T_TYPE' => 'B',
					'LN_SIZE' => 6,
					'BG_COLOR' => 'transparent',
					'BRD_COLOR' => array(0,0,0),
					'BRD_SIZE' => 0.2,
					'BRD_TYPE' => '1',
// // 					'BRD_TYPE_NEW_PAGE' => '',
					'TEXT' => '',
					);
					
	$table_kartu_kendali = array(
					'WIDTH' => 6,
					'T_COLOR' => array(0,0,0),
					'T_SIZE' => 10,
					'T_FONT' => 'Arial',
					'T_ALIGN' => 'C',
					'V_ALIGN' => 'T',
					'LN_SIZE' => 7,
					'BG_COLOR' => 'transparent',
					'BRD_COLOR' => array(0,0,0),
					);
										
	$table_nota_header_type = array(
					'WIDTH' => 6,
					'T_COLOR' => array(0,0,0),
					'T_SIZE' => 9,
					'T_FONT' => 'Arial',
					'T_ALIGN' => 'C',
					'V_ALIGN' => 'M',
					'T_TYPE' => 'B',
					'LN_SIZE' => 4,
					'BG_COLOR' => 'transparent',
					'BRD_COLOR' => array(0,0,0),
					'BRD_SIZE' => 0.2,
					'BRD_TYPE' => '1',
// // 					'BRD_TYPE_NEW_PAGE' => '',
					'TEXT' => '',
					);					
	$table_default_header_type_Apotik = array(
					'WIDTH' => 6,
					'T_COLOR' => array(0,0,0),
					'T_FONT' => 'times',
					'T_ALIGN' => 'C',
					'V_ALIGN' => 'T',
					'T_TYPE' => 'B',
					'LN_SIZE' => 8,
					);
	$table_default_data_type = array(
					'T_COLOR' => array(0,0,0),
					'T_SIZE' => 10,
					'T_FONT' => 'Arial',
// 					'T_ALIGN' => 'N',
					'V_ALIGN' => 'M',
					'T_TYPE' => '',
					'LN_SIZE' => 5,
					'BG_COLOR' => array(255,255,255),
					'BRD_COLOR' => array(0,0,0),
					);
	$table_default_Prinsip = array(
					'T_COLOR' => array(0,0,0),
					'T_SIZE' => 12,
					'T_FONT' => 'arial',
					'V_ALIGN' => 'M',
					'T_TYPE' => '',
					'LN_SIZE' => 5.5,
					'BG_COLOR' => 'transparent',
					'BRD_COLOR' => array(255,255,255),
					'BRD_SIZE' => 0.2,
					);
	$table_default_IUK = array(
					'T_COLOR' => array(0,0,0),
					'T_SIZE' => 12,
					'T_FONT' => 'times',
					'V_ALIGN' => 'M',
					'T_TYPE' => '',
					'LN_SIZE' => 6,
					'BG_COLOR' => 'transparent',
					'BRD_COLOR' => array(255,255,255),
					'BRD_SIZE' => 0.2,
					);
	$table_default_Penolakan = array(
					'T_COLOR' => array(0,0,0),
					'T_SIZE' => 12,
					'T_FONT' => 'times',
					'V_ALIGN' => 'M',
					'T_TYPE' => '',
					'LN_SIZE' => 5.5,
					'BG_COLOR' => 'transparent',
					'BRD_COLOR' => array(255,255,255),
					'BRD_SIZE' => 0.2,
					);					
	$table_default_TDP = array(
					'T_COLOR' => array(0,0,0),
					'T_SIZE' => 12,
					'T_FONT' => 'times',
// 					'T_ALIGN' => 'N',
					'V_ALIGN' => 'M',
					'T_TYPE' => '',
					'LN_SIZE' => 10,
					'BG_COLOR' => 'transparent',
					'BRD_COLOR' => array(0,0,0),
					'BRD_SIZE' => 0.2,
// 					'BRD_TYPE' => '0',
// 					'BRD_TYPE_NEW_PAGE' => '',
					);
	$table_default_TDP_type = array(
					'TB_ALIGN' => 'L',
					'L_MARGIN' => 0,
					'BRD_COLOR' => array(0,0,0),
					'BRD_SIZE' => 0.2,
// 					'BRD_TYPE' => '0',
					);
	$table_default_IMB = array(
					'T_COLOR' => array(0,0,0),
					'T_SIZE' => 12,
					'T_FONT' => 'arial',
					'V_ALIGN' => 'M',
					'T_TYPE' => '',
					'LN_SIZE' => 5,
					'BG_COLOR' => 'transparent',
					'BRD_COLOR' => array(255,255,255),
					'BRD_SIZE' => 0.2,
					);
	$table_default_Ternak = array(
					'T_COLOR' => array(0,0,0),
					'T_SIZE' => 12,
					'T_FONT' => 'times',
					'V_ALIGN' => 'M',
					'T_TYPE' => '',
					'LN_SIZE' => 5,
					'BG_COLOR' => 'transparent',
					'BRD_COLOR' => array(0,0,0),
					'BRD_SIZE' => 0.3,
					);
	$table_default_Apoteker_a4 = array(
					'T_COLOR' => array(0,0,0),
					'T_SIZE' => 12,
					'T_FONT' => 'times',
					'V_ALIGN' => 'M',
					'T_TYPE' => '',
					'LN_SIZE' => 6,
					'BG_COLOR' => 'transparent',
					'BRD_COLOR' => array(0,0,0),
					'BRD_SIZE' => 0.3,
					);
	$table_default_Apoteker_letter = array(
					'T_COLOR' => array(0,0,0),
					'T_SIZE' => 12,
					'T_FONT' => 'times',
					'V_ALIGN' => 'M',
					'T_TYPE' => '',
					'LN_SIZE' => 5,
					'BG_COLOR' => 'transparent',
					'BRD_COLOR' => array(0,0,0),
					'BRD_SIZE' => 0.3,
					);
	$table_default_Laboratorium = array(
					'T_COLOR' => array(0,0,0),
					'T_SIZE' => 12,
					'T_FONT' => 'arial',
					'V_ALIGN' => 'M',
					'T_TYPE' => '',
					'LN_SIZE' => 7,
					'BG_COLOR' => 'transparent',
					'BRD_COLOR' => array(0,0,0),
					'BRD_SIZE' => 0.3,
					);
	$table_default_Fisioterapis = array(
					'T_COLOR' => array(0,0,0),
					'T_SIZE' => 12,
					'T_FONT' => 'arial',
					'V_ALIGN' => 'M',
					'T_TYPE' => '',
					'LN_SIZE' => 7,
					'BG_COLOR' => 'transparent',
					'BRD_COLOR' => array(0,0,0),
					'BRD_SIZE' => 0.3,
					);
	$table_default_Optik = array(
					'T_COLOR' => array(0,0,0),
					'T_SIZE' => 11,
					'T_FONT' => 'times',
					'V_ALIGN' => 'M',
					'T_TYPE' => '',
					'LN_SIZE' => 4,
					'BG_COLOR' => 'transparent',
					'BRD_COLOR' => array(0,0,0),
					'BRD_SIZE' => 0.3,
					);
	$table_default_Optik1 = array(
					'T_COLOR' => array(0,0,0),
					'T_SIZE' => 10,
					'T_FONT' => 'arial',
					'V_ALIGN' => 'M',
					'T_TYPE' => '',
					'LN_SIZE' => 4,
					'BG_COLOR' => 'transparent',
					'BRD_COLOR' => array(0,0,0),
					'BRD_SIZE' => 0.3,
					);
	$table_default_IMB_type = array(
					'TB_ALIGN' => 'L',
					'L_MARGIN' => 0,
					'BRD_COLOR' => array(255,255,255),
					'BRD_SIZE' => 0.2,
					);
	$table_default_MIRAS = array(//$table_default_sertifikat
					'T_COLOR' => array(0,0,0),
					'T_SIZE' => 9,
					'T_FONT' => 'arial',
					'V_ALIGN' => 'M',
					'T_TYPE' => '',
					'LN_SIZE' => 5,
					'BG_COLOR' => 'transparent',
					'BRD_COLOR' => array(255,255,255),
					'BRD_SIZE' => 0.2,
					);
	$table_default_sertifikat = array(
					'T_COLOR' => array(0,0,0),
					'T_SIZE' => 14,
					'T_FONT' => 'times',
					'V_ALIGN' => 'M',
					'T_TYPE' => '',
					'LN_SIZE' => 7,
					'BG_COLOR' => 'transparent',
					'BRD_COLOR' => array(255,255,255),
					'BRD_SIZE' => 0.2,
					);
	$table_default_Disnakertrans = array(
					'T_COLOR' => array(0,0,0),
					'T_SIZE' => 12,
					'T_FONT' => 'arial',
					'V_ALIGN' => 'M',
					'T_TYPE' => '',
					'LN_SIZE' => 7,
					'BG_COLOR' => 'transparent',
					'BRD_COLOR' => array(255,255,255),
					'BRD_SIZE' => 0.2,
					);
	$table_default_Apotik = array(
					'T_COLOR' => array(0,0,0),
					'T_SIZE' => 11,
					'T_FONT' => 'times',
					'V_ALIGN' => 'M',
					'T_TYPE' => '',
					'LN_SIZE' => 6,
					'BG_COLOR' => 'transparent',
					'BRD_COLOR' => array(0,0,0),
					'BRD_SIZE' => 0.2,
					);
	$table_default_Dokter = array(
					'T_COLOR' => array(0,0,0),
					'T_SIZE' => 12,
					'T_FONT' => 'helvetica',
					'V_ALIGN' => 'M',
					'T_TYPE' => '',
					'LN_SIZE' => 8,
					'BG_COLOR' => 'transparent',
					'BRD_COLOR' => array(0,0,0),
					'BRD_SIZE' => 0.2,
					);
	$table_default_Dokter1 = array(
					'T_COLOR' => array(0,0,0),
					'T_SIZE' => 12,
					'T_FONT' => 'helvetica',
					'V_ALIGN' => 'M',
					'T_TYPE' => '',
					'LN_SIZE' => 6,
					'BG_COLOR' => 'transparent',
					'BRD_COLOR' => array(0,0,0),
					'BRD_SIZE' => 0.2,
					);
	$table_default_Apotik1 = array(
					'T_COLOR' => array(0,0,0),
					'T_SIZE' => 11,
					'T_FONT' => 'times',
					'V_ALIGN' => 'M',
					'T_TYPE' => '',
					'LN_SIZE' => 4.5,
					'BG_COLOR' => 'transparent',
					'BRD_COLOR' => array(0,0,0),
					);
	$table_default_Penolakan = array(
					'T_COLOR' => array(0,0,0),
					'T_SIZE' => 13,
					'T_FONT' => 'times',
					'V_ALIGN' => 'M',
					'T_TYPE' => '',
					'LN_SIZE' => 6,
					'BG_COLOR' => 'transparent',
					'BRD_COLOR' => array(255,255,255),
					);					
	$table_default_perikanan1 = array(
					'T_COLOR' => array(0,0,0),
					'T_SIZE' => 10,
					'T_FONT' => 'times',
					'V_ALIGN' => 'M',
					'T_TYPE' => '',
					'LN_SIZE' => 5,
					'BG_COLOR' => 'transparent',
					'BRD_COLOR' => array(0,0,0),
					'BRD_SIZE' => 0.3,
					);
	$table_default_budidaya = array(
					'T_COLOR' => array(0,0,0),
					'T_SIZE' => 12,
					'T_FONT' => 'times',
					'V_ALIGN' => 'M',
					'T_TYPE' => '',
					'LN_SIZE' => 7,
					'BG_COLOR' => 'transparent',
					'BRD_COLOR' => array(255,255,255),
					'BRD_SIZE' => 0.3,
					);
	$table_default_perikanan2 = array(
					'T_COLOR' => array(0,0,0),
					'T_SIZE' => 12,
					'T_FONT' => 'times',
					'V_ALIGN' => 'M',
					'T_TYPE' => '',
					'LN_SIZE' => 7,
					'BG_COLOR' => 'transparent',
					'BRD_COLOR' => array(0,0,0),
					'BRD_SIZE' => 0.3,
					);
	$table_default_nota = array(
					'T_COLOR' => array(0,0,0),
					'T_SIZE' => 10,
					'T_FONT' => 'arial',
					'V_ALIGN' => 'M',
					'T_TYPE' => '',
					'LN_SIZE' => 5,
					'BG_COLOR' => 'transparent',
					'BRD_COLOR' => array(0,0,0),
					'BRD_SIZE' => 0.3,
					);
	$table_default_tangkapIkan = array(
					'T_COLOR' => array(0,0,0),
					'T_SIZE' => 9,
					'T_FONT' => 'arial',
					'V_ALIGN' => 'M',
					'T_TYPE' => '',
					'LN_SIZE' => 6,
					'BG_COLOR' => 'transparent',
					'BRD_COLOR' => array(0,0,0),
					'BRD_SIZE' => 0.3,
					);
	$table_default_SKAU = array(
					'T_COLOR' => array(0,0,0),
					'T_SIZE' => 11,
					'T_FONT' => 'arial',
					'V_ALIGN' => 'M',
					'T_TYPE' => '',
					'LN_SIZE' => 5,
					'BG_COLOR' => 'transparent',
					'BRD_COLOR' => array(0,0,0),
					'BRD_SIZE' => 0.3,
					);
	$table_default_SKAU1 = array(
					'T_COLOR' => array(0,0,0),
					'T_SIZE' => 10,
					'T_FONT' => 'arial',
					'V_ALIGN' => 'M',
					'T_TYPE' => '',
					'LN_SIZE' => 5,
					'BG_COLOR' => 'transparent',
					'BRD_COLOR' => array(0,0,0),
					'BRD_SIZE' => 0.2,
					);
	$table_default_SKMI = array(
					'T_COLOR' => array(0,0,0),
					'T_SIZE' => 13,
					'T_FONT' => 'times',
					'V_ALIGN' => 'M',
					'T_TYPE' => '',
					'LN_SIZE' => 6,
					'BG_COLOR' => 'transparent',
					'BRD_COLOR' => array(0,0,0),
					'BRD_SIZE' => 0.3,
					);
	$table_default_SKMI1 = array(
					'T_COLOR' => array(0,0,0),
					'T_SIZE' => 13,
					'T_FONT' => 'times',
					'V_ALIGN' => 'M',
					'T_TYPE' => '',
					'LN_SIZE' => 8,
					'BG_COLOR' => 'transparent',
					'BRD_COLOR' => array(0,0,0),
					'BRD_SIZE' => 0.3,
					);
	$table_default_RIPHHK = array(
					'T_COLOR' => array(0,0,0),
					'T_SIZE' => 11,
					'T_FONT' => 'helvetica',
					'V_ALIGN' => 'M',
					'T_TYPE' => '',
					'LN_SIZE' => 5,
					'BG_COLOR' => 'transparent',
					'BRD_COLOR' => array(0,0,0),
					'BRD_SIZE' => 0.2,
					);
	$table_default_RIPHHK1 = array(
					'T_COLOR' => array(0,0,0),
					'T_SIZE' => 11,
					'T_FONT' => 'helvetica',
					'V_ALIGN' => 'M',
					'T_TYPE' => '',
					'LN_SIZE' => 6,
					'BG_COLOR' => 'transparent',
					'BRD_COLOR' => array(0,0,0),
					'BRD_SIZE' => 0.2,
					);
	$table_default_RIPHHK2 = array(
					'T_COLOR' => array(0,0,0),
					'T_SIZE' => 11,
					'T_FONT' => 'helvetica',
					'V_ALIGN' => 'M',
					'T_TYPE' => '',
					'LN_SIZE' => 6,
					'BG_COLOR' => 'transparent',
					'BRD_COLOR' => array(0,0,0),
					'BRD_SIZE' => 0.2,
					);
	$table_default_RIPHHK3 = array(
					'T_COLOR' => array(0,0,0),
					'T_SIZE' => 11,
					'T_FONT' => 'helvetica',
					'V_ALIGN' => 'M',
					'T_TYPE' => '',
					'LN_SIZE' => 6,
					'BG_COLOR' => 'transparent',
					'BRD_COLOR' => array(0,0,0),
					'BRD_SIZE' => 0.2,
					);
	$table_default_SKAU1_type = array(
					'TB_ALIGN' => 'L',
					'L_MARGIN' => 0,
					'BRD_COLOR' => array(0,0,0),
					'BRD_SIZE' => 0.2,
					);
	$table_default_perikanan1_type = array(
					'TB_ALIGN' => 'L',
					'L_MARGIN' => 0,
					'BRD_COLOR' => array(0,0,0),
					'BRD_SIZE' => 0.2,
					);
	$table_default_Apotik_type = array(
					'TB_ALIGN' => 'L',
					'L_MARGIN' => 0,
					'BRD_COLOR' => array(0,0,0),
					'BRD_SIZE' => 0.2,
					);
	$table_default_table_type = array(
					'TB_ALIGN' => 'L',
					'L_MARGIN' => 0,
					);
	$table_default_table_type1 = array(
					'TB_ALIGN' => 'L',
					'L_MARGIN' => 0,
					);
/*****************************************************
TABLE DEFAULT DEFINES --- END
*****************************************************/
?>